### ISSUE TITLE
[BUG] The minimum resize size of the window hides the title bar buttons.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ayasa520/waydroid-helper#11]
### Describe the bug

When resized to its minimum width, the title bar buttons are hidden:

![Screenshot_20241123_154323](https://github.com/user-attachments/assets/71cce5af-b174-46c6-b977-59e768369dfd)

### Device

Linux Desktop

### Operating System

1. <details>

   ```bash
   #!/usr/bin/env -S bash
   kinfo
   ```

   </details>

1. > ```YAML
   > Operating System: Fedora Linux 41
   > ```

### Kernel version

> ```YAML
> Kernel Version: 6.11.9-300.fc41.x86_64 (64-bit)
> ```

### Desktop Environment

> ```YAML
> KDE Plasma Version: 6.2.3
> ```

### GPU

> ```YAML
> Graphics Processor: AMD Radeon RX 5700
> ```

### Logs

Are these necessary for *this*?

**Comment by ayasa520** [comment]
I recently released a Fedora build, could you give it a try?
```
sudo dnf copr enable cuteneko/waydroid-helper
sudo dnf install waydroid-helper
```

**Comment by ayasa520** [comment]
![image](https://github.com/user-attachments/assets/828701e5-e594-484c-aa7c-66e509487fd1)
https://github.com/ayasa520/waydroid-helper/commit/53db4691fda503d88d348ddf995eb8bffbc8503c should fix it.
