### ISSUE TITLE
[BUG] run.log created in ~ every time waydroid-helper is launched

### ISSUE THREAD

**Issue by cobbdzon** [ayasa520/waydroid-helper#14]
### Describe the bug

Maybe put the log in one of the standard folders apps use like maybe in `~/.local/share/waydroid-helper/logs`

### Device

Linux Desktop

### Operating System

CachyOS Linux x86_64

### Kernel version

6.12.6-2-cachyos

### Desktop Environment

GNOME 47.2

### GPU

NVIDIA GeForce RTX 2050

### Logs

N/A

**Comment by ayasa520** [comment]
This has already been fixed but has not yet been released. 

[stop shitting logs under home folder #12](https://github.com/ayasa520/waydroid-helper/pull/12)
