### ISSUE TITLE
Doesn't launch.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ayasa520/waydroid-helper#2]
#### **Logs**

1.	```sh
	pwsh -Command "& '/home/RokeJulianLockhart/AppImages/waydroid_helper.appimage'"
	```

	> ```log
	> ResourceUnavailable: Program 'waydroid_helper.appimage' failed to run: An error occurred trying to start process '/home/RokeJulianLockhart/AppImages/waydroid_helper.appimage' with working directory '/home/RokeJulianLockhart'. No such file or directoryAt line:1 char:1
	> + & '/home/RokeJulianLockhart/AppImages/waydroid_helper.appimage'
	> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
	> ```
	
1.	```
	bash -c "'/home/RokeJulianLockhart/AppImages/waydroid_helper.appimage'"
	```

	> ```
	> bash: /home/RokeJulianLockhart/AppImages/waydroid_helper.appimage: cannot execute: required file not found
	> ```

#### **Environment**

1.	I've installed https://github.com/ayasa520/waydroid-helper/releases/download/v0.1.0/waydroid-helper-0.1.0-x86_64.AppImage.
1.	I'm using https://download.fedoraproject.org/pub/fedora/linux/releases/40/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.14.iso.

**Comment by ayasa520** [comment]
Do you use an integration tool like AppimageLauncher?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ayasa520/waydroid-helper/issues/2#issuecomment-2395062865

@ayasa520, per https://github.com/ayasa520/waydroid-helper/issues/3#issue-2567971477, I've tried this in GearLever. I wanted to use `appimagelauncher` (per https://github.com/TheAssassin/AppImageLauncher/discussions/666#discussion-7279488) but haven't been able to ascertain how to get it to integrate AppImages into the application launcher.

**Comment by ayasa520** [comment]
@RokeJulianLockhart
 https://github.com/ayasa520/waydroid-helper/releases/download/v0.1.0/waydroid-helper-0.1.0-x86_64.AppImage
 I've just released a new version of the appimage. Could you please try it?
 I installed Fedora on a VM, and waydroid-helper works fine on it 
![image](https://github.com/user-attachments/assets/72b3b512-709e-4893-86bf-6c7da5008c0f)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ayasa520/waydroid-helper/issues/2#issuecomment-2395359885

@ayasa520, I might need 10 weeks to test – I haven't forgotten. Thanks.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ayasa520/waydroid-helper/issues/2#issuecomment-2395359885

@ayasa520, that indeed appears to work:

1.	> ![Screenshot_20241025_173213](https://github.com/user-attachments/assets/a030dbc1-7fcd-4236-bfae-781bd0ca1ae3)
1.	> ![Screenshot_20241025_173432](https://github.com/user-attachments/assets/51f49e68-ae8b-4e42-a16e-346839aa9557)

Thank you!
